### ISSUE TITLE
Walking off ledges

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#13]
I'm just speculating but currently the ant can only jump off a ledge where there is a link node.  So if you were to destroy a hole in the ground the ants wouldn't actually go through that hole.  This is why it was recommended to use the NAV mesh, but I currently haven't found any other viable methods.

**Comment by elliotnaylor** [comment]
update:  I got the AI to move to a single location without using the NAV mesh, this means the AI will not take the safest path and can fall off of ledges.

**Comment by elliotnaylor** [comment]
Ready for testing!

**Comment by BojanStankovic** [comment]
Hey @ScaryEme, have you used/installed a "Substance" plugin by any chance? I have cloned the repo and when opening the project it said the project is using it and it needs to be installed. It is possible that the plugin is part of the University's UE4 installation, so just wanted to check it out

**Comment by elliotnaylor** [comment]
I definitely haven't, but to make sure i'll download it onto my home PC tomorrow.  I wouldn't be surprised if it is used in uni considering it reduces texture file sizes.

https://www.unrealengine.com/marketplace/substance-plugin

**Comment by BojanStankovic** [comment]
Cool, thanks @ScaryEme

**Comment by rbakerusw** [comment]
I have tested the current version and so far I haven't encountered any bugs. It all seems to work perfectly.

**Comment by napiorek** [comment]
Just finished the testing and it looks promising. Haven't found anything wrong with it, I also mange to add some extra node for them to follow.
:+1:

**Comment by BojanStankovic** [comment]
Tested, no errors

**Comment by BojanStankovic** [comment]
Merged to master. Closing

**Comment by BojanStankovic** [comment]
I'm reopening the issue since some additional work was done in its branch. After a chat with Elliot he said he continued working on this branch even though it was merged and the issue related to it closed. Since no new issue was created to describe what was done, @ScaryEme could you write relevant updates here?

**Comment by elliotnaylor** [comment]
Completely changed the AI and moved away from node to node movement and went onto directional movement.  The old form of movement has been kept in case of future use.

* Ant will run in set starting direction

* Added a node that sends the ant in north, south, east or west

* When an ant hits a wall and the speed is changed to 0 the ant will run in the opposite direction

**Comment by BojanStankovic** [comment]
Merging the new changes brought the bug into the master branch. This is the consequence of no tests being done by other team members before the merge. In order to prevent similar things happening in the future I will update the workflow slightly. Please refer to #14 for updates to come

**Comment by BojanStankovic** [comment]
Since this is merged but has a bug I'm closing this issue and a new one will be opened because @ScaryEme  will branch from a buggy master
