### ISSUE TITLE
Interactivly add new NAV nodes

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#15]
Elliot's navigation nodes for moving the ants work nicely. They need to be added at runtime to control where the ant will go next. Assigned to myself

**Comment by BojanStankovic** [comment]
I managed to make the nodes spawn on user keyboard event. Next goal is to spawn them at the position user is looking at, snapped to the ground. I will need to setup each new node so it is connected to the previous one

**Comment by elliotnaylor** [comment]
We've moved away from using nodes but I will reopen this if we start using them again

**Comment by BojanStankovic** [comment]
@ScaryEme 
How have we moved away? We still have the nodes that change the direction of an ant, no? Is there a different way to change the direction of an ant?
