### ISSUE TITLE
Mining / Digging

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#16]
Issue for Ryan's task that enables the ants to dig through the terrain. Task's progress was initially documented in Basecamp: [Mining/Digging - basecamp](https://public.3.basecamp.com/p/pQyNhLN6Y5vqELut3hcLbDat)

**Comment by rbakerusw** [comment]
I am currently looking into creating a mesh and a blueprint that will cause the mesh to decrease in scale then disappear to create the effect of digging. I will also need a particle effect to make it more realistic but for now I will need to make sure the scaling works before adding anything else.

**Comment by rbakerusw** [comment]
New update: I have created a cube that will shrink by 0.1 every second (I can alter how quick it shrinks this is just for testing purposes). I just need to add the destroy actor when it hits a certain size but i have noticed a slight issue where the shape will shrink in size from the top and the bottom so the shape starts to look like it is floating.

I am currently looking into this.

Edit: The actor will now destroy itself when it equals a certain size.

**Comment by rbakerusw** [comment]
I encountered a new issue where the timer would still try to shrink the box even though the box had been destroyed.

Update: I managed to fix this by destroying the trigger box as well as deleting the box.

**Comment by BojanStankovic** [comment]
Even though I can't recreate the issue with scaling since I'm at work at the moment, I'm guessing that the problem is with where the origin for your geometry is positioned. Lets say you have a cube and its origin is in the centre of that object (usually the default behaviour). If you apply scale factor of <1 to it, uniformly in all directions, it will behave exactly as you would expect. All sides would shrink towards the centre equally. If you apply only z-axis scaling it will shrink only vertically (by its height), again equally in both directions. Now let's say you move the origin from the centre and snap it to the bottom side. If you apply z-axis scale factor <1 now, it should behave quite differently. The effect you should get is that it reduces its height while remaining positioned on the floor. If the origin is snapped to the bottom side and in its centre, when you apply scaling in all directions it will change the size of the model in all directions while remaining "stuck" to the floor.

If this is the case then it is not a bug but a way most software works with 3D models.

Hope it helps :)

**Comment by rbakerusw** [comment]
I looked into changing the origin but the only guides I've found so far claim I can't do it within the engine. It says I have to use some other software to do it.

**Comment by rbakerusw** [comment]
Bojan and Tom M helped me adjust the scale so the scaling effect will only effect an object from one side rather than an equal amount on both sides. Now all I need to add is AI to trigger the event rather than the player.

**Comment by rbakerusw** [comment]
I have uploaded a new version that is almost ready for merging after some fixes and testing.

New features:
-Trigger boxes will now only activate when a digger ant is in the box.
-Left mouse button will now highlight an ant if you are looking at one.
-Right mouse button will set a highlighted ant to dig.
-When Digging, the ant will stop moving and stand still for the rest of the level.

Need to be fixed:
-Once an ant has been set to highlighted is wont un-highlight.

If you test the new version and find any issues please post it here.

After this is completed then it will be ready for merging so I can then add the digging animation (when it is completed) and I will also swap the Right Mouse Button and link the digging to the HUD instead.

Edit (08/12/2016):

I have fixed the issue where the ant would not un-highlight so now the player can click on and off ants with no issues.
This branch is now ready for merging as soon as someone tests it to make sure there are no errors.

**Comment by rbakerusw** [comment]
This feature has been fully implemented so I am closing the issue.

**Comment by BojanStankovic** [comment]
Reopening just to remind myself to merge it

**Comment by BojanStankovic** [comment]
It seems that everything is working as expected. However I got an error warning after exiting the game. I will merge this branch now but I'll open a new issue as a bug report so we can fix this as soon as possible.

**Comment by BojanStankovic** [comment]
Merged, closing
