### ISSUE TITLE
Ant model

### ISSUE THREAD

**Issue by napiorek** [PlaceholderGames/2016-VnD_Game#17]
The goal is to come up with  model of ant base on human body (so the ant will walk on two legs)
Examples :
[](url)
![73938](https://cloud.githubusercontent.com/assets/22525895/19806805/05321c4e-9d15-11e6-8f04-8875e2828eab.jpg)
![l78663-cartoon-ant-43724](https://cloud.githubusercontent.com/assets/22525895/19806821/1154591a-9d15-11e6-98ec-3520c1320b83.jpg)

**Comment by elliotnaylor** [comment]
The first one looks perfect for the job

**Comment by BojanStankovic** [comment]
Agree, first one looks great! It would be cool if you can rig the antennas as well so they point to some direction (can be utilized later on)

**Comment by rbakerusw** [comment]
Yes, I agree with what Elliot and Bojan said. The second one doesn't really look that appealing, it looks more like an enemy compared to the first one.

I don't know what to think about the shoes though.

**Comment by ghost** [comment]
I like the first one too, I think aiming for cartoony rather than photo realistic will make the game more fun for this genre anyways! :)

**Comment by napiorek** [comment]
This issue is ready for testing and any suggestions.

**Comment by rbakerusw** [comment]
I looked at the animations and they look really good. It looked like they were realistic and no bugs so far.

**Comment by ghost** [comment]
Can we get an image of our ant model here for reference? or a small video attachment? If its possible ofcourse! :)

**Comment by napiorek** [comment]
Ant model has been chosen and already used in the game, hence this issue can be closed
