### ISSUE TITLE
Mini-Map?

### ISSUE THREAD

**Issue by ghost** [PlaceholderGames/2016-VnD_Game#18]
Should we have a mini-map as apart of the HUD? What do you guys think?

**Comment by rbakerusw** [comment]
We could but i'm not sure, Since you will be above looking down onto the map you should be able to see most things. If the map gets too big then we would need a mini map.

**Comment by elliotnaylor** [comment]
If there are 3 platforms on top of each other how would you tell which platform the ant is on.  I don't think  it's really necessary and it would limit our map designs.

**Comment by rbakerusw** [comment]
What do you mean by 3 platforms?

Edit: After explaining this to me, I understand what you mean by the platforms and the fact that the mini-map would not be very effective.

**Comment by BojanStankovic** [comment]
If I remember correctly we decided there wouldn't be much use for the mini map. I'll close it, but if any potential use for the map comes clear we can always reopen it
