### ISSUE TITLE
Bug with AI node movement

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#19]
I noticed a funny bug with AI movement through nodes. If for some reason we have a node that is pointing to itself or if it is the only node in the map, the AI actor will go crazy and start spinning in circles. Some boundary condition could be useful. Effect does look funny though :)

**Comment by elliotnaylor** [comment]
Thanks for pointing this out! As it's unlikely to happen i'll get to it after finishing the AI just to polish it.

**Comment by elliotnaylor** [comment]
I'm going to shelf this one for now considering we have moved away from node to node movement.  If we go back to it I will reopen this issue
