### ISSUE TITLE
Game ideas

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#2]
We've been throwing around a lot of ideas based around VR gaming.  The first game we came up with involved the user exploring a world, collecting objects, building and progressing in the world.  

The second idea involved the user shrinking down to particle size and moving around from particle to particle.  The ideas were ultimately scraped due to being unable to move around an area.  The only method we could use is teleporting which would get tedious over time.

We eventually came up with an idea where you would act as a god in a world of ant people.  Similar to lemmings you would maneuver them to the end of the level trying to save as many of them as you can.

**Comment by BojanStankovic** [comment]
Since ant people are the road we all decided to go I will close this issue
