### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by napiorek** [PlaceholderGames/2016-VnD_Game#20]
The aim is to create a pickaxe and shovel for mining/digging animation and attached it to character.

**Comment by napiorek** [comment]
I was working on my branch, trying to attach the tool to character, and it turns out that original ThirdPersonBP has been turn into Third Person Character ( then one with integrated camera ) and second copy has the AI attached to it, hence working with it is kind of impossible as when added to scene it imminently following the node.

I tried to export clean copy of ThirdPersonCharacter from a new 3rd person project, and place it in Content folder of my project, but that didn't work.

So the question is, can I just duplicate AI_Ant and then remove any extra blue prints from it ?

**Comment by napiorek** [comment]
This branch is no longer needed and it will not be updated or used.
The work will continue on the branch I20_new_tool_branch

**Comment by napiorek** [comment]
This branch include animation for ant and tools like shovel or pickaxe.
The socket for the tool also has been added so the tool can be attached to the ant model.

**Comment by BojanStankovic** [comment]
This was merged to the develop branch so @napiorek can have work done by @rbakerusw in order to continue with the tool implementation
