### ISSUE TITLE
2 ants going into the same collision box

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#24]
If 2 ants go into the same collision area 1 will stop until the next collision box is hit.  I need a way of checking if multiple ants are going into a collision box.

**Comment by elliotnaylor** [comment]
After redesigning the AI movement the collision boxes no longer work.  I will keep this issue on hold until they are back up to date.

**Comment by elliotnaylor** [comment]
Never mind a very simple change fixed this issue

**Comment by rbakerusw** [comment]
If this issue has been solved is it ok if we close it? So we know its finished.

**Comment by elliotnaylor** [comment]
It was solved in the latest commit
