### ISSUE TITLE
First deadline for a playable build

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#25]
After discussing (Piotr and Richard were consulted remotely) we decided to set 23.02.2017 as the first deadline for a playable build. Following components (only most essential features) are required to outline this build:
- Splash screen
- Start screen
- Goal
- End game conditions
- End screen
- Basic game mechanics
- UI
- A simple level that demonstrates the game mechanics

**Comment by rbakerusw** [comment]
I am happy with this deadline if everyone else is as long as it doesn't overlap other coursework.

**Comment by ghost** [comment]
I'm happy with it too, I'm going to do a crunch at my house the week before the deadline, anyone is welcome to come will include pizzas and munch and coffee or some drinks, we could also do this at the uni? :)

**Comment by napiorek** [comment]
First playable build done and conclusions are being discuses in the issue #52 Important: Second build.

**Comment by BojanStankovic** [comment]
Sorry @napiorek for re-opening one more of the issues you closed, but I need to merge the 1st build into the master before closing the issue 😜

**Comment by BojanStankovic** [comment]
Merged into the master branch. Tested, works. Closing the 1st build
