### ISSUE TITLE
UI screens

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#27]
This includes:
- splash screen
- initial menu screen
- in game menu screen
- end screen (win/lose)

A hint: an "end screen" can be implemented regardless off the win/lose condition. Who ever is assigned to this task can use a dummy trigger for the end screen for development purposes.

**Comment by ghost** [comment]
Has anyone been assigned to this task yet?

**Comment by BojanStankovic** [comment]
You can see the "Assignees" at the top of the right sidebar in the issue, as well as some other relevant information like "Milestone" for example :wink: I took this issue 4 days ago

**Comment by BojanStankovic** [comment]
I have created a simple main menu from which it is possible to:
- start the game
- enter the options menu (WIP)
- quit the game

I used a tutorial that can be found here: https://www.youtube.com/watch?v=ulUO4EN8BG8

To do:
- ~~intro screen~~
- ~~in game menu~~
- end game message
- ~~end game menu~~

**Comment by BojanStankovic** [comment]
Introduction screen is added. It is displayed when the game starts and it transitions to the "main menu" screen after seconds.

**Comment by BojanStankovic** [comment]
The in-game menu is added. It is triggered by releasing the "P" key.

**Comment by BojanStankovic** [comment]
The end-game menu is added. Since we don't have the end-game condition at this point I have created a variable "AntsAmount" int the level and set it to 3. By hitting the "Spacebar" key, that variable is decremented by 1. When it reaches 0, the "Game Over" menu is displayed. It also pauses the game.

**Comment by BojanStankovic** [comment]
This is ready to be reviewed

**Comment by rbakerusw** [comment]
I just tested the menus and all the button worked fine. I could only find 1 issue with it, you have to double click on the in game menu.

**Comment by BojanStankovic** [comment]
Fixed the focusing on the menu once it is displayed during the game

**Comment by ghost** [comment]
Great work Bojan, I will test it now and leave you some feedback! :)

**Comment by BojanStankovic** [comment]
Fixing the focusing on the widget caused problems with mouse movement controls when resuming the game. When the game is resumed player can look around only while holding down any of the mouse buttons. Moving through the world is not affected

**Comment by BojanStankovic** [comment]
I have disabled focusing to the "in-game menu" widget at the time being. The blueprint is still there but it is not attached to anything. I have merged it so we have the functionality of the screens. The bug is only a minor one, but I will open an issue for it. Closing...
