### ISSUE TITLE
Dynamically changing the animiation of an ant

### ISSUE THREAD

**Issue by napiorek** [PlaceholderGames/2016-VnD_Game#30]
Rather than remove/swap the character to perform certain activity (like digging) the blue print for swapping the ant animation is needed.

**Comment by BojanStankovic** [comment]
Renamed the issue to keep the consistency. GitHub automatically assigns the number for the issue.

**Comment by napiorek** [comment]
To create the blueprint that will change the animation of an ant I need to incorporate it with #16.
BojanStankovic sugested to create a Develop branch that will include #16 and the branch #20

**Comment by napiorek** [comment]
I modify the BP of the ThirdPerson so it change the Ant animation from running to digging(if triggered)

![image](https://cloud.githubusercontent.com/assets/22525895/22559990/d60643e4-e96a-11e6-84f6-8d19da76acdc.png)

**Comment by napiorek** [comment]
Also added the option to pause the Ant as this was helpful during developing the game.

**Comment by napiorek** [comment]
Button 2 will trigger forward digging (horizontal) and button 3 will trigger digging in vertical direction ( down) and in both cases the animation will be assign accordingly

**Comment by napiorek** [comment]
Task has been accomplished, ready for testing!

**Comment by BojanStankovic** [comment]
Tested and merged to 'develop'. Great stuff. Closing
