### ISSUE TITLE
Bug Report: AI Ant Keeps Moving

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#33]
With the new AI movement, there is an issue with the AI Ant. the issue is that the Ant keeps swapping direction while standing on the spot when it has been set to dig.

To recreate this bug, click on an ant and set it to dig. You will see that is keeps flipping between looking north and south or east and west.

**Comment by elliotnaylor** [comment]
This is on my side, the code currently swaps the ant in opposite direction when movement is 0.  So I have added a boolean in #45 called used which you can call in the animations.

**Comment by elliotnaylor** [comment]
Ryan is going to walk me through doing it, since it's his code.  Took 2 seconds

**Comment by BojanStankovic** [comment]
Merged, contains all changes done in #45. Closing
