### ISSUE TITLE
 Bug Report: Mouse Tracer Colliding with Trigger Box

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#34]
Sometimes when you try to click and highlight an Ant to get them to dig, the tracer will collide with the trigger box. This makes it hard to select an ant when they are inside a box.

![tracerbug](https://cloud.githubusercontent.com/assets/22525915/22590880/675d0e1a-ea09-11e6-8658-9a049bb07f33.png)

At first glance, a quick fix maybe to try and lower the trigger box into the ground a bit more so it only overlaps the characters feet and not the body.

**Comment by rbakerusw** [comment]
I have created a temporary fix for this by altering the Z value so the trigger box only covers the ants feet and not their whole body.

**Comment by BojanStankovic** [comment]
Merged. Closing
