### ISSUE TITLE
Bug report: HUD and UI warning message

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#36]
Hey @Richard-Chaos , after viewing your branch I had a following message pop-up after simulating the game:

![bug_screenshot](https://cloud.githubusercontent.com/assets/11376143/22613990/127efb4e-ea75-11e6-9c46-1b9d6098c3db.png)

I'm not sure what it means and I have merged the branch anyway. If you decide to tackle this bug please create a new branch like any other, referring to this issue number.

**Comment by ghost** [comment]
Ok I’ll get right on fixing this bug, I have an idea of what might be causing it.  It shouldn’t be to difficult.

**Comment by ghost** [comment]
I’ve managed to fix this bug; the warning messages no longer show in the message log. This issue is now ready for review and merging, it can then be closed.

**Comment by BojanStankovic** [comment]
Tested. Merged. Closing
