### ISSUE TITLE
Spawning the ants at the beginning of the level

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#37]
I was just testing Richard's branch with the HUD and realized that we don't have a spawning method for the ants. We'll have to introduce this together with a variable that will hold the current amount of the ants (antsAmount). 'antsAmount' can be then connected to the HUD where the total amount of ants is displayed

**Comment by rbakerusw** [comment]
I think Elliot said he was going to start working on a spawner at the start of each level for the ants. I'm not sure if he has started it or not since he was ill this week. It might be best to message him first to ask.

**Comment by BojanStankovic** [comment]
I have only opened the issue and left it unassigned. If he started doing it already he was supposed to open the issue, if not and he is about to start, then he has the issue ready 😉

**Comment by elliotnaylor** [comment]
Still working on polishing the AI but I will assign this to myself as soon as i'm happy

**Comment by elliotnaylor** [comment]
I'm starting on this today ready for the first build.

**Comment by elliotnaylor** [comment]
I implemented a basic spawner, but the AI that was spawned by the spawner don't obey the same rules i've set to the ones I spawned myself.  The ants will turn in the set direction but only run in 1 direction.  This is very confusing to me since the AI ant has code that makes the ant run in the direction it's facing.

**Comment by elliotnaylor** [comment]
After testing I found the get control rotation isn't working with dynamically spawned actors.  I can't find a fix for this so i'm going to upload the current version and discuss it with my team.

**Comment by elliotnaylor** [comment]
The turning of the ants is now fixed along with a working spawner, about to commit.

**Comment by BojanStankovic** [comment]
@ScaryEme What happened with this issue? I know we have a spawner now but I can see that the branch is not merged. Was it recreated in one of the other branches or some other scenario occurred?

**Comment by rbakerusw** [comment]
I am pretty sure he recreated on a different version so the other branch was merged instead since it was more up to date.

**Comment by elliotnaylor** [comment]
Forgot to mention that I added this to the develop branch manually as there would be too many conflicts.  It was just easier

**Comment by BojanStankovic** [comment]
It doesn't look like you added it to the develop, it must have been done somewhere else but it remained undocumented. Please try to document what you do. It is actually more important than making the game  😃
