### ISSUE TITLE
Quantum Shift (old concept)

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#4]
# Game concept
## Main concept

The character is trapped in a locked cell unable to walk around but he has a suit that allows him to shrink down to the quantum level which is then only place the character can teleport.  Something to consider is that the space is technically 3 dimensional where the ground is the actual particles, you can travel in any direction as long as you can reach it.  The quantum realm would look something like below:

![image](https://cloud.githubusercontent.com/assets/22525909/19390047/52660838-921e-11e6-8313-9c077d73dcbd.png)
Taken from Marvels Antman

Occasionally a particle will have an effect, whether it drains your energy, gives you energy, blows up, etc.  As you progress in the game you will be able to travel to further away particles that will take you to new areas. 
## Energy

The player will have energy or oxygen which can only recharge in the normal world.  The player will have to carefully manage their time and decide whether they can make it to certain particles before dying.  Some particles might give you oxygen/energy to live longer allowing you to progress further.
## Normal size

You can get out of the quantum realm by standing on a particular particle (escape node) which will take you out to a set location in the normal world.  In that location (where you can’t walk) you will be able to pick up items and recharge your energy.  For example you might find a key for a chest, but the chest is behind a wall.  So the only way you could get to it is to go into the quantum realm and find another escape node to the location with the chest.
## Enemies (possibility)

Something other than the Energy needs to keep the player moving from particle to particle.  The player needs to know that it’s not a safe place and that he can’t spend much time there.  The enemies would spawn in when you’ve been in the quantum realm for about 1 minute, where they will start chasing you and draining your energy/oxygen.  You do not have any way of attacking the enemies so the only thing you can do is escape using the escape node.  Richard pointed out that it should look something like below (taken from the matrix) except made of out electric.

![image](https://cloud.githubusercontent.com/assets/22525909/19390077/72092c38-921e-11e6-9fcf-5c1e82c365d7.png)
Sentinel Robots from the Matrix

Thanks, feel free to add any mechanics I missed,
Elliot

**Comment by BojanStankovic** [comment]
Thanks @ScaryEme, great to have this documented here. Closing the issue
