### ISSUE TITLE
Attaching the tool to an Ant

### ISSUE THREAD

**Issue by napiorek** [PlaceholderGames/2016-VnD_Game#41]
This is to spawn a tool on the event of changing ant status, e.g. from running to digging.

**Comment by napiorek** [comment]
Spawning the different tool for each animation is working now.

**Comment by napiorek** [comment]
Now I just have to change the pivot of the static mesh of the tool, and after excessive research I come to the conclusion that this should be done in 3D program like 3D Max or Blender, rather than in UE4. 
Source - https://forums.unrealengine.com/showthread.php?1140-Manually-changing-the-pivot-of-an-actor

**Comment by napiorek** [comment]
Adjusted the pivot of the Shovel and scaled it so it looks better in the hand of Ant.  Also added the texture for shovel so it look more realistic now.

**Comment by napiorek** [comment]
All done and ready for review and to be merge  @BojanStankovic !

**Comment by BojanStankovic** [comment]
Unfortunately this is not ready to merge. The shovel is not in the good possition and there is something wrong with the 3rd person character's view. Screenshots attached
![3rdpersonview_bug](https://cloud.githubusercontent.com/assets/11376143/23333892/fe27bc44-fb8b-11e6-919e-0c2db511e3ea.png)
![shoveldisplacement](https://cloud.githubusercontent.com/assets/11376143/23333893/ff4072b0-fb8b-11e6-9702-6febab4d465d.png)

**Comment by BojanStankovic** [comment]
Another issue **not** related to @napiorek is that this branch is still not using macros. I will create a new branch from the current develop and manually recreate as many changes as possible. This would have to be done anyway so lets do it the safe way with a new branch.

**Comment by BojanStankovic** [comment]
@napiorek A new branch, named **I41_Attaching_the_tool_to_an_ant**, has all the changes done on the branch ~~I40_Attaching_the_tool_to_an_ant~~ as well as the latest stuff from the develop branch. It also introduces a compiling error when migrating to macros. We can try to fix this next week.

**Comment by napiorek** [comment]
That weird view is because I change the  3rd person mech to Ant, but we already agree to get rid of 3rd person .

**Comment by napiorek** [comment]
Did you push the I41 branch, as I'm not able to checkout in to it ?

**Comment by napiorek** [comment]
Solved ! Turns out I had to checkout to develop and pull the latest build ;)

**Comment by BojanStankovic** [comment]
It is pushed. You can always double check it on here on GitHub. As for the weird view it is true that we will get rid of the mesh, but I still can't merge something that has an obvious bug. What was the reason for changing the mesh? Maybe you can revert it back to original one?

I'm free if you need any help with git

**Comment by napiorek** [comment]
Many thanks to @BojanStankovic  for solving the compiled error on this branch !
Now I can carry on and polish the pivot/offset of the tools

**Comment by napiorek** [comment]
I'm currently having an Issue on the new branch (I41_Attaching_tool_to_an_ant)
The animation switching is working, but no tool is being attached, where on my previous branch I40_Attaching_tool_to_an_ant it works fine (beside the pivot).

**Comment by napiorek** [comment]
To try to solved it I manually copied the BP mechanism from I40 to I41 branch and that didn't work.
Will try something else, but any ideas/suggestions are welcome !

**Comment by BojanStankovic** [comment]
Branch I41 has nothing special about it. As I wrote when I switched it, I recreated what I saw was changed. I might have missed something and that is why you need to go through it and check what might be missing. This would have to be done anyway since the old branch was not using macros and was completely incompatible with the current state of the project.

Try to go through what you did on the old branch to make it work and recreate it on the new one.

**Comment by BojanStankovic** [comment]
Ok, I fixed the problem of tools not being spawned. The problem was in a duplicated logic for animation switching. I have modified the animation switcher macro so it has outputs in order to continue the logic for tool spawning after this macro node. The duplicate logic is removed.

The tool spawning node logic still needs to be placed in a macro but there is an issue around it that causes a compiling error. We'll have to do some research on this since I couldn't solve it at this time.

**Comment by napiorek** [comment]
Fixed the collision Ants with a tool  (PickAxe)

![image](https://cloud.githubusercontent.com/assets/22525895/23629069/68787858-02ae-11e7-8f92-18ea4a3f3c81.png)

**Comment by napiorek** [comment]
Ready to be review and merge

**Comment by BojanStankovic** [comment]
Tested, merged. Closing
