### ISSUE TITLE
Implement Macros for the existing blueprints

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#42]
With the implementation of Macros, blueprints become cleaner and easier to maintain and work on with other people. Macros also enable code reuse throughout the project with a restriction that a Macro library must be the same class type as the parent class for whatever the Macro is going to be used with.

The existing blueprints should be cleaned up.

**Comment by BojanStankovic** [comment]
The documentation and the tutorial used to implement Macros:
https://docs.unrealengine.com/latest/INT/Engine/Blueprints/UserGuide/Macros/
https://www.youtube.com/watch?v=pj5buBQ0lHU

**Comment by ghost** [comment]
Hey bojan, I've already used functions for code reuse throughout the hud class, is that ok?

**Comment by BojanStankovic** [comment]
I'm not sure. The purpose of the Macros might be different. Read the documentation I posted a link to, as well as go through the tutorial so you can compare them to the functions.

**Comment by BojanStankovic** [comment]
AI_Ant and ThirdPersonCharacter blueprints now have macros. The level blueprint is different than any other blueprint and at this point I didn't find a way to have a separate macro library for it. Instead I have just used the macros to contain the mess of nodes in logical parts.

The problem with the level blueprint might be solved if the level code is done somewhere else. I'll ask this on the 2nd year help-desk.

Ready for reviewing.

**Comment by BojanStankovic** [comment]
Tested and merged. Closing...
