### ISSUE TITLE
Bug: HUD displaying over Main Menu

### ISSUE THREAD

**Issue by ghost** [PlaceholderGames/2016-VnD_Game#43]
A bug has turned up from recent merges to the master branch that causes the HUD to be shown while the player is on the Main Menu and Introduction scenes, this is unintentional and needs to be fixed.

I’ll assign myself to this issue and attempt to resolve it.

**Comment by ghost** [comment]
I’ve manage to isolate the bug and fix it, the HUD is only displayed while a player is on a Level scene as intended.

This issue is ready for review and merging.

**Comment by ghost** [comment]
In this bug fix I've changed the project settings so that the “Introduction” scene is the first scene shown when the game is built as a stand-alone application.  I’ve also set the default scene opened by the game engine to “ThirdPersonLevel” as its the one we're currently implementing features too.

For the “Introduction and Main Menu” scenes the Game Mode should be set to “GameMode” This is the default one used by Unreal.  It doesn’t include the HUD blueprint.

For each scene that is a Level, the Game Mode should be set to “ThirdPersonLevel”.  This Game Mode includes the HUD blueprint, its only intended to be shown while on a level scene.

**Comment by BojanStankovic** [comment]
Works! Merged and fixed the merge conflicts by doing some manual recreation. It seems that by modifying the settings.ini related to a level modifies that level somehow as well. I don't know what exactly though. Closing
