### ISSUE TITLE
Bug report: Ant can use more than one skill

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#44]
Currently there is an issue in the game that allows the ants to be set to digging then the player can set the ant to something else even though it has been used.

I will work on fixing this bug when I have time. At first look, we may need an additional variable to prevent the ant from being used again.

**Comment by rbakerusw** [comment]
I think I have now fixed this issue to prevent the ants from being used more than once.

**Comment by BojanStankovic** [comment]
Tested, merged! Closing
