### ISSUE TITLE
Merge to develop

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#45]
There are going to be a lot of conflicts and there aren't that many changes so I am going to do it by myself.

**Comment by elliotnaylor** [comment]
I am not going to commit this to the develop branch yet because the kamakaze macro is not outputting an explosion even when set.  I changed it as a test earlier but it hasn't changed back.

**Comment by BojanStankovic** [comment]
Since #33 was branched from the branch for this issue it contains all the updates. Therefor, the branch for this issue will remain unmerged. Closing
