### ISSUE TITLE
Bug report: digging/mining is treated as one

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#47]
There is an issue when you set an ant to digging or mining where they dig both ways. For example, if you set an ant to mining he can dig down and forwards and the same for setting an ant to digging. We need a way to separate the 2 so mining will only go forwards and digging will only go down.

Since I created the digging/mining I will try to look at my code to solve this issue.

**Comment by rbakerusw** [comment]
I have now separated the 2 types of digging. There are now 2 trigger boxes, one should be used when you want to dig and the other for when you want to mine.

This way digging will no longer trigger mining and vice versa.

**Comment by BojanStankovic** [comment]
This is ok as a temporary solution, however we will have to come up with a way that will enable the tool to be triggered anywhere on the map. There is really no point if a certain tool can be activated only where level designer decides it can be used. Sometimes you want to provide several possible outcomes at a single position on a map, but only one will enable solving the puzzle (or passing to the next stage)

**Comment by BojanStankovic** [comment]
Merged. Closing
