### ISSUE TITLE
Ants stack when running into block being dug

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#49]
When the ant is digging the block movement isn't 0 which means the ants won't turn around.  This means the ants will stack at this time.

I can fix this by turning the ant on collision with the block as well as movement being 0

**Comment by elliotnaylor** [comment]
Still slightly buggy, but good enough for the first build of the game

**Comment by BojanStankovic** [comment]
Works. Merged. Closing...
