### ISSUE TITLE
Ant tool that spawns direction node

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#50]
This is usually Ryans job but considering all the code is there and the change direction node is my work I figured I would implement it into a tool.

**Comment by elliotnaylor** [comment]
Just finished adding.  If any of you have any recommendation for controls then i'd like to hear them.

Current controls:
5 = north
6 = south 
7 = east
8 = west

**Comment by elliotnaylor** [comment]
It's kind of hard to tell where the ant is going so i'm adding an arrow to show the direction the ants will run in.  This is on the change direction node

**Comment by elliotnaylor** [comment]
This is now finished and ready for merging

**Comment by BojanStankovic** [comment]
This works great @ScaryEme! The way user interacts will have to be modified, but the current keys 5, 6, 7, 8 are good enough. Maybe we can put them on WASD since they modify the direction of movement. Anyway, good work here.
Merged with no conflict. Closing...
