### ISSUE TITLE
Ants fall through the diggable box

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#51]
For some reason ants fall through the box they are supposed to dig instead of walking over it. Just by quick overview I couldn't find the cause for this. There is also an issue with the box that is supposed to be mined where some ants will walk through it.

We might need to come up with a different solution for destruct-able boxes.

**Comment by rbakerusw** [comment]
Hmm, thats weird everything was working fine on the previous build. Must be something to do with the ants collision possibly.

**Comment by BojanStankovic** [comment]
It can be seen in action on my level design branch I26_BOJAN_....

**Comment by rbakerusw** [comment]
Yeah, I have noticed it in mine to. It happens once you start digging block then the other ants will ignore it but only when one is in the middle of digging.

**Comment by napiorek** [comment]
That does not happens to me, when one Ants digging other just bounce off the cube and run in opposite direction.

**Comment by rbakerusw** [comment]
I started working on my level again today and the issue no longer occurs for some reason so I'm not sure what caused/causes it.

**Comment by BojanStankovic** [comment]
That is very strange. We should look more into this during the class today

**Comment by elliotnaylor** [comment]
This was caused by the ants stack branch.  Where I stopped the ants being blocked by the cube in order to get a collision trigger to turn it around.  This works fine with the mining block, but at the time I didn't realize the mine and the dig block were the same thing

I'll just disable the ants stack fix for now and come up with a better way to fix it

**Comment by elliotnaylor** [comment]
I fixed this issue by removing my ant stack #49 fix.  This is not a massive issue so i'll reopen it #49 as a minor bug
