### ISSUE TITLE
End condition

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#55]
I am about to start working on implementing the end condition to the game.  Whether it's win or lose.

**Comment by elliotnaylor** [comment]
Currently I finished implementing an end goal, which will print a message saying the ants have won if the amount of ants hit a set amount.

**Comment by elliotnaylor** [comment]
Just finished adding the end game to the tools, so once all ants are used or destroyed it will print an end game message

**Comment by elliotnaylor** [comment]
Currently they only print messages but I intend these to be replaced with an end game hud that has been implemented

**Comment by elliotnaylor** [comment]
Added the actual end game screen, deleted the ants after a short amount of time and fixed a small bug where the end game screen wouldn't appear.  The only noticeable issue now is that the ants can end the game early by applying multiple tools to an ant.  This can be fixed in #44

**Comment by ghost** [comment]
As a side note, I’ve added a secondary end game condition.  When the levels timer runs out the game now ends.  I’ve implemented this in the branch dedicated to issue #59.

**Comment by BojanStankovic** [comment]
A reminder here: develop branch is broken by this merge so @ScaryEme and I need to fix it as soon as possible because nothing else can be merged at this point.

Things broken:
- goal doesn't remove the ant
- end condition isn't triggered (only the one with spacebar is)
- Kamikaze ant doesn't get removed after the explosion

**Comment by BojanStankovic** [comment]
@ScaryEme fixed this. The problem was with references. This is now fully merged into the develop and operational. Closing the issue
