### ISSUE TITLE
Resetting node when location can't be reached

### ISSUE THREAD

**Issue by elliotnaylor** [PlaceholderGames/2016-VnD_Game#6]
**What i've done**
I decided to start working on the AI movement.  It works by simply moving from node to node all held in an array.  Each individual node will tell the AI where to move next, once it lands on that area it will start to move towards the next node.

**Idea**
Currently I have it set on a timer so if it doesn't reach a node in 5 seconds it assumes the AI is lost and sends it to the previous one.  In this scenario in the final game the player would have to use a number of abilities to make the path possible.  Therefore moving the AI to the next area and trapping ones that can no longer reach.

**Problem**
Currently simply taking one away from the array value simply moves the AI to a random spot away from all the nodes.  Overall it comes down to me not using arrays in unreal before, so if any of you have any ideas please let me now.

Thanks, 
Elliot

**Comment by elliotnaylor** [comment]
I know we haven't assigned tasks yet but I really wanted to test if the core element in the game is viable as early as possible.

**Comment by BojanStankovic** [comment]
Good effort Elliot, at this point I can't give you much feedback since there is not enough info for me, but would like to hear more during the meeting.

**Comment by BojanStankovic** [comment]
@ScaryEme I don't know if this is done already, but just in case here is something Mike was explaining on white board - [tile system series in Unity](https://www.youtube.com/watch?v=kYeTW2Zr8NA). Idea should be the same for Unreal I suppose.

**Comment by elliotnaylor** [comment]
Still haven't fixed this issue, i've done a lot of research and found that you can check if there is a valid path via a behavior tree.  I currently don't know much about how they work but I will keep researching.

**Comment by elliotnaylor** [comment]
We discussed in class today that we would simply have the player try to walk to the location, but if the ant hits the wall he will simply turn around and go back to the previous node.  Something i need to remember is that the ants should never actually stop moving at any point to avoid clumping.

**Comment by elliotnaylor** [comment]
I have done a lot more testing and research and I have only ran into dead ends.  I would like to meet up and discuss this thoroughly very soon as I might have to completely restart the AI due to limitations.

**Comment by rbakerusw** [comment]
Ok, when do you want to discuss this? Thursday during the lesson or earlier?

**Comment by elliotnaylor** [comment]
Sounds good, I just want to hear ideas and make sure i'm going about it the right way

**Comment by elliotnaylor** [comment]
A possible method I just discussed with Ryan is simply having them move to the closest node while ignoring the z (up/down) coordinate.  So at any point if an ant is stranded it will check the distance to the closest node and run directly towards it.

**Comment by BojanStankovic** [comment]
What is the status on this since we had some breakthroughs with AI movement? 😃
Maybe we can close the issue @ScaryEme ?

**Comment by elliotnaylor** [comment]
The movement has been completely changed and this issue no longer applies.
