### ISSUE TITLE
Bug Report: Warning in ThirdPersonCharacter Blueprint

### ISSUE THREAD

**Issue by ghost** [PlaceholderGames/2016-VnD_Game#61]
There's a warning message displayed in the ThirdPersonCharacter Blueprint regarding the KamikazeAnimation macro, I'm not sure how this effects the game but I thought I'd point it out.

I noticed it while creating the flying camera.

![image](https://cloud.githubusercontent.com/assets/22819171/23561726/5f5f03b4-0037-11e7-9058-45cfc9b76e4c.png)

**Comment by BojanStankovic** [comment]
This is a duplicate of issue #56 

Closing...
