### ISSUE TITLE
Suggestion: Reset Level Option

### ISSUE THREAD

**Issue by ghost** [PlaceholderGames/2016-VnD_Game#62]
I think its going to be necessary for our game to include a reset option, possibly as a choice on the in-game pause menu.  As there are certain situations that could occur than makes it impossible for the player to complete the level.  I've seen this feature in other games within this genre and it works well.

What do you all think?

**Comment by BojanStankovic** [comment]
I agree. It can improve the user experience because right now if user wants to restart the level they need to go to the main menu first.

**Comment by elliotnaylor** [comment]
I love this idea as you wouldn't always be able to get to the end of the level depending on how many ants you've wasted, i'll add it to the build 2 list #52

**Comment by rbakerusw** [comment]
We just need to add a restart button to the pause menu so the user can retry the level. We already have a button that resets the game.

**Comment by BojanStankovic** [comment]
I have added the "Restart Level" button to the end game screen and the pause game screen

**Comment by napiorek** [comment]
Tested the "Reset" button and it works, so it can be merge.

**Comment by BojanStankovic** [comment]
Merged. Closing
