### ISSUE TITLE
Adding some basic colour to blocks

### ISSUE THREAD

**Issue by rbakerusw** [PlaceholderGames/2016-VnD_Game#70]
I think we should add some basic colours to the different cubes throughout the game so it makes it easier for the player to see what blocks is part of the map and which ones can be dug etc.

Maybe we could have something like:

- grey for mining to look like a stone
- brown for digging to look like dirt
- maybe we can leave the basic map white

**Comment by BojanStankovic** [comment]
I would like to take this because I want to play with the materials in UE4 a bit 😃

**Comment by BojanStankovic** [comment]
I created two basic materials. One for the mining blocks and one for diggable area. Textures used for them were acquired from here:
http://freepbr.com/materials/limestone-rock-pbr-material/

These materials still require some improvement, but for the purpose of differentiating them during gameplay they should do fine for now.

**Comment by napiorek** [comment]
Just tested it and have not found any flaws. Well done @BojanStankovic :+1:

**Comment by BojanStankovic** [comment]
Merged. Closing
