### ISSUE TITLE
Bug report: spawner still doesn't direct the ant as required

### ISSUE THREAD

**Issue by BojanStankovic** [PlaceholderGames/2016-VnD_Game#74]
I thought I fixed this problem by adding invisible walls to the spawner without any collision for them and then enabling the collision base on the direction ants are supposed to go to. However, a direction node was there all the time so the ants would go in the right direction because of it during the tests.

I'll fix this ASAP

**Comment by BojanStankovic** [comment]
This was an easy fix. The type of collision being set depending on the direction passed was wrong. It should work now

**Comment by rbakerusw** [comment]
I just tested this feature and it works fine. The first ant will go in the direction you set and will no longer run off in a random direction.

**Comment by BojanStankovic** [comment]
Merged. Closing
