### ISSUE TITLE
UE version in J208

### ISSUE THREAD

**Issue by napiorek** [PlaceholderGames/2016-VnD_Game#79]
I tried to run our game on one of the PC at J208 and apparently the engine version has been updated to 4.15 and 4.14.3 
The version we were using in our project is no longer available (4.13).

![ue version](https://cloud.githubusercontent.com/assets/22525895/25657964/5462c2c0-2ff8-11e7-88c1-03db067b536a.png)

![warning](https://cloud.githubusercontent.com/assets/22525895/25657967/58d1303a-2ff8-11e7-95fb-6127e8e9adb6.png)

**Comment by rbakerusw** [comment]
Do you know if any other pcs have updated?

**Comment by napiorek** [comment]
I only checked a few of them, and lucky some PC's still got the 4.13 version on it.

**Comment by BojanStankovic** [comment]
Mike answered this issue on the helpdesk repo. Mike's answer:
"Right, short term get Rob, Mike or Martin, the CS technicians to install 4.13 on your machine. I'll email them and ask for 4.13 to be put in all the PCs"

Closing...
