### ISSUE TITLE
Skill: Kamikaze

### ISSUE THREAD

**Issue by ghost** [PlaceholderGames/2016-VnD_Game#8]
Once enabled the targeted ant has ability to destroys objects blocking pathways, such as mud, boulders, enemy Grasshoppers. (This skill can also kill nearby ants if it isn't timed correctly)

Global variables = (object target_ant = null)

Internal variables = (boolean kamikaze_enabled = false, int countdown = 5)

Objects = (explosion_collision_area  = (x, y, z))

Pseudo code:

The player targets a ant by clicking them, this sets the target_ant object variable to the clicked ant, the kamikaze_enabled Boolean will be set to true, the countdown in will decremented by 1 every second, once the countdown reaches 0, the target_ant will be destroyed and an explosion_collision_area will be created anything inside that collision area will be destroyed including mud. stones, enemy grasshoppers and even friendly ants.

Deadline: Undecided at the moment.

**Comment by rbakerusw** [comment]
What is the current thoughts about this feature?

Since I have finished the digging I am free to work on this if you want me to as long as we are still including this feature.

**Comment by BojanStankovic** [comment]
Maybe we can have an element that will enable a self destruction on an ant when it is assigned to it. This could be a explosive acid perhaps and the ant can become extremely red just before bursting. This action would melt/destroy any objects in near vicinity that are destructible when in contact with the acid

**Comment by rbakerusw** [comment]
Since we decided on including this feature, I will start working on it.

**Comment by rbakerusw** [comment]
Just a quick update. In the latest kamikaze version you can now:

- Set ant to kamikaze mode
- After 3 seconds the ant will blow up
- Destructible mesh that will get destroy if in explosion radius

Known issues:

-Explosion particle effect wont disappear after explosion (but since we are eventually swapping particle effect, this may not be a problem in the future

**Comment by rbakerusw** [comment]
I have updated this. changes:

- Balanced impulse of explosion
- Decreased radius of explosion
- Skill is now linked to key 4 not 2
- Debris now disappears after a certain amount of time

Just need to decide how long the delay for the explosion will be.
What happens if the explosion hits the ant.

**Comment by rbakerusw** [comment]
This should be ready for testing now. To test it, drag a destructible mesh onto the screen from the meshes folder. Place an ant near the destructible and click on the ant and press 4 after a slight delay the ant should blow up.

**Comment by rbakerusw** [comment]
The kamikaze skill has been moved to a macro to prevent merging conflicts.

**Comment by BojanStankovic** [comment]
Works, merged into the develop. Closing...
